name: Tests

on: [push, pull_request, workflow_dispatch]


jobs:
  run-test:
    runs-on: debian-11
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: pip install pytest yarl

      - name: Run tests
        run: pytest